version: '3'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mushrooms_recognition
    restart: always
    networks:
      - bot_network
networks:
  bot_network:
    driver: bridge
